import{S as a,N as h,P as f,a as w,A as b}from"./assets/vendor-285bacc2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const y=document.querySelector(".header-btn"),i=document.querySelector(".backdrop");function g(){i.classList.remove("backdrop--hide"),i.classList.add("backdrop--show")}y.addEventListener("click",g);const v=document.querySelector(".mobmenu__close");v.addEventListener("click",l);function l(){i.classList.remove("backdrop--show"),i.classList.add("backdrop--hide")}const S=document.querySelector(".menu-btn"),L=document.querySelector(".header-menu");function d(){L.classList.toggle("visually-hidden")}S.addEventListener("click",d);const u=Array.from(document.querySelectorAll(".header-menu-link"));u.push(document.querySelector(".header-order"));for(const t of u)t.addEventListener("click",o=>{o.preventDefault(),document.getElementById(t.getAttribute("href")).scrollIntoView({behavior:"smooth"}),d()});const m=Array.from(document.querySelectorAll(".mobmenu-link"));m.push(document.querySelector(".mobmenu-order"));for(const t of m)t.addEventListener("click",o=>{o.preventDefault(),document.getElementById(t.getAttribute("href")).scrollIntoView({behavior:"smooth"}),l()});const q="https://portfolio-js.b.goit.study/api/reviews",p=document.querySelector(".review-list"),A=document.querySelector(".review-buttons-wrapper");async function k(){return(await w.get(q)).data}k().then(t=>{E(t),new a(".swiper",{direction:"horizontal",updateOnWindowResize:!0,slidesPerView:1,swipeHandler:".reviews-list-item",speed:400,breakpoints:{768:{slidesPerView:2,spaceBetween:16},1440:{slidesPerView:4,spaceBetween:18}},navigation:{prevEl:".previous-btn",nextEl:".next-btn"},keyboard:{enabled:!0},mousewheel:{invert:!0}})}).catch(t=>{p.innerHTML=`<li class="error-item">
       <p class="error-title">Oops, something went wrong 😢</p>
       <p class="error-text-describe">Problems with downloading content from the server. Error: ${t.message}</p>
    </li>`,A.classList.add("hide")});function E(t){const o=t.map(({avatar_url:n,author:s,review:e})=>`
        <li class="review-item swiper-slide">
          <img class="review-avatar" src="${n}" alt="author avatar"/>
          <p class="review-author-name">${s}</p>
          <p class="review-author-text">${e}</p>
        </li>`).join("");p.insertAdjacentHTML("beforeend",o)}a.use([h,f]);const P=Array.from(document.querySelectorAll(".accordion-container"));new b(P,{elementClass:"item",triggerClass:"btn-arrow-toggl",panelClass:"item-text",onOpen:function(t){console.log(t.querySelector("svg")),t.querySelector("button").classList.add(".is-rotate")}});
//# sourceMappingURL=commonHelpers.js.map
